### ISSUE TITLE
Rust Mülkiyet Kavramı Kitabının Github'a yüklenmesi

### ISSUE THREAD

**Issue by rust-lang-tr** [rust-lang-tr/dokuman#5]
Rust Programlama dilinin bel kemiği olan mülkiyet kavramının ele alındığı belgenin Github üzerine taşınması, dildeki gelişimler doğrultusunda güncellenmesinin sağlanması

**Comment by mertataol** [comment]
Fasikülün en son iyileştirilmeleri de kapsayacak şekilde genişletilmesi gerekmekte. Dikkate alınacağını umuyorum. 
İyi çalışmalar dilerim.
